### ISSUE TITLE
滚动到底没有更多数据时不显示没有更多数据

### ISSUE THREAD

**Issue by wotermelon** [3Spiders/react-fast-scroll#15]
设备：小米手机等高分屏，高DPI，都会出现这样的问题

现象：当加载几页后到达底部，没有数据的时候，底部是空白的，既不出现没有更多数据，也不显示加载重试，就是空白。

猜测：是因为 scrollTop 获取的是小数，而clientHeight 获取的是整数导致的。

**Comment by 3Spiders** [comment]
需要告诉该框架，数据已经加载完了。
框架会显示“没有更多数据”。

**Comment by wotermelon** [comment]
@carrollcai 用的是仓库中的demo……没有任何更改，在chrome上正常
